name: Emraors
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - hspec
  - QuickCheck
  - transformers
  - mtl
  - free

data-dir: data

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-unused-top-binds

library:
  source-dirs:
    - recursionSchemes
    - arrows
    - freeMonads
    - lambdaCalculus 
